## Getting Started
#
# Follow this guide to get the workflow: https://docs.github.com/en/actions/how-tos/write-workflows/use-workflow-templates
#
## How to Use AI reviews?
# 
# 1. On your pull request add "leanix-ci" as reviewer and wait for the workflow to finish!
#
## Customizing the AI reviewer
#
# You can set `review-instructions` as path to repository specific review instructions.
# Furthermore you can provide more context about your repository in context-files that
# you can point to in `include-context-files`.
#
# # Feedback?
#
# Let us know what you think in Slack: #team-butterfly
#
name: AI Code Review
on:
  pull_request:
    types: [review_requested]

jobs:
  review:
    name: PR Review
    if: github.event.requested_reviewer.login == 'leanix-ci'
    runs-on: ubuntu-latest
    steps:
      - name: Get credentials
        uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}

      - name: Decode and set AICORE_SERVICE_KEY
        run: |
          decoded_secret=$(echo "${{ env.GITHUB_REVIEW_ACTION_AICORE }}" | base64 --decode)
          echo "AICORE_SERVICE_KEY=$decoded_secret" >> $GITHUB_ENV

      - uses: leanix/shared-github-workflows/ai-review@main
        with:
          # Specify the AI model to be used for creating reviews
          model: gpt-4o
          # Path to the review instructions file, which guides the AI in evaluating the code changes (e.g. ".github/review-instructions.md").
          review-instructions: ""
          # A comma separated list of files to review. Supports glob patterns
          include-files: "**"
          # A comma separated list of files excluded from review. Supports glob patterns
          exclude-files: package-lock.json
          # Specify how previous AI review comments should be handled (e.g., hide or keep).
          previous-results: hide
          # Specify additional context files for AI review, using comma-separated values and supporting glob patterns.
          include-context-files: ""
          # List context files to exclude from AI review, using comma-separated values and supporting glob patterns.
          exclude-context-files: ""
          # SAP BTP AI Core service key
          aicore-service-key: ${{ secrets.AICORE_SERVICE_KEY }}
          # Specify the GitHub user token for the account that posts AI-generated review comments (Defaults to github-actions[bot])
          github-user-token: ${{ env.CD_BOT_BUTTERFLY }}
